name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test

      # Upload Playwright HTML report
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      # Zip only the downloaded files and set output
      - name: Zip downloaded files
        id: zip_downloaded_files
        if: ${{ !cancelled() }}
        run: |
          DOWNLOAD_DIR=".artifacts/downloadFile"
          ZIP_FILE=".artifacts/downloadFile.zip"

          echo "Contents of $DOWNLOAD_DIR before zip:"
          ls -al "$DOWNLOAD_DIR" || echo "Directory not found"

          if [ -d "$DOWNLOAD_DIR" ]; then
            zip -r "$ZIP_FILE" "$DOWNLOAD_DIR"
            if [ -f "$ZIP_FILE" ]; then
              echo "zip_created=true" >> $GITHUB_OUTPUT
              echo "ZIP file created successfully: $ZIP_FILE"
            else
              echo "zip_created=false" >> $GITHUB_OUTPUT
              echo "Failed to create ZIP file"
            fi
          else
            echo "No downloaded files found"
            echo "zip_created=false" >> $GITHUB_OUTPUT

      # Upload zipped downloaded files as workflow artifact
      - name: Upload downloaded files as artifact
        if: ${{ !cancelled() && steps.zip_downloaded_files.outputs.zip_created == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-files
          path: .artifacts/downloadFile.zip
          retention-days: 30

      # Add the ZIP file reference to GitHub Actions summary
      - name: Add downloaded files to summary
        if: ${{ !cancelled() && steps.zip_downloaded_files.outputs.zip_created == 'true' }}
        run: |
          echo "### Downloaded Files" >> $GITHUB_STEP_SUMMARY
          echo "You can download the ZIP file from the Artifacts section above." >> $GITHUB_STEP_SUMMARY
