name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      
      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Zip downloaded files
        id: zip_downloaded_files
        if: ${{ !cancelled() }}
        run: |
          DOWNLOAD_DIR=".artifacts/downloadFile"
          ZIP_FILE=".artifacts/downloadFile.zip"
          if [ -d "$DOWNLOAD_DIR" ]; then
            cd .artifacts
            zip -r downloadFile.zip downloadFile
          else
            echo "No downloaded files found"
          fi

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          draft: false
          prerelease: false

      - name: Upload downloaded files to Release
        if: ${{ !cancelled() && steps.zip_downloaded_files.conclusion == 'success' && -f .artifacts/downloadFile.zip }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .artifacts/downloadFile.zip
          asset_name: downloadFile.zip
          asset_content_type: application/zip

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() && steps.zip_downloaded_files.conclusion == 'success' }}
        with:
          name: downloaded-files
          path: .artifacts/downloadFile.zip
          retention-days: 30

      - name: Add downloaded files to summary
        if: ${{ !cancelled() }}
        run: |
          if [ -f .artifacts/downloadFile.zip ]; then
            echo "### Downloaded Files" >> $GITHUB_STEP_SUMMARY
            echo "You can download the ZIP file from the Artifacts section above or from the GitHub Release assets." >> $GITHUB_STEP_SUMMARY
          fi
